apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::<YOUR_ACCOUNT_ID>:role/OpsUser
      username: ops-viewer
      groups:
        - ops-viewers