apiVersion: v1
kind: Namespace
metadata:
  name: ops
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ops-view-only
  namespace: ops
subjects:
  - kind: User
    name: ops-viewer
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
